version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      python-dependencies:
        applies-to: version-updates
        patterns: ['*']
    open-pull-requests-limit: 3
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        applies-to: version-updates
        patterns: ['*']
    open-pull-requests-limit: 3
